import MainNav from "@/components/MainNav";
import Backdrop from "@/components/ui/backdrop";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
    title: "Invoice Management System",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <Backdrop />
            <div className="relative flex max-h-screen">
                <div className="w-16">
                    <MainNav />
                </div>
                <div className="w-full h-full max-h-screen min-h-screen overflow-y-scroll ">
                    <div className="max-w-screen-2xl mx-auto ">{children}</div>
                </div>
            </div>
        </>
    );
}
