-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "CustomerCredit" SET DEFAULT 0,
ALTER COLUMN "CustomerCredit" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "LineItem" ADD COLUMN     "ItemNumber" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "amount" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Part" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "ReturnedInvoice" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(65,30);
