import type { Metadata } from "next";
import { Mada } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import { Toaster } from "@/components/ui/toaster";
import ToasterModalProvider from "@/providers/toaster";
import { AddNewProductModal } from "@/components/addProductModal";
import { Providers } from "./providers";
import { ThemeProvider } from "@/providers/theme-provider";
import prismaDb from "@/lib/prisma";
import Backdrop from "@/components/ui/backdrop";

const inter = Mada({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
    title: "Invoice Management System",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const products = await prismaDb.product.findMany();
    const categories = await prismaDb.catgories.findMany();
    const units = await prismaDb.units.findMany();
    return (
        <html lang="ar" dir="rtl">
            <body className={`${inter.className}    min-h-screen bg-gray-400 `}>
                <Providers>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {/* <div className="absolute top-[50%] left-[50%] translate-y-[-50%] translate-x-[-50%] z-0 blur-[90px] rounded-full w-[70%] h-[60%] sm:w-[520px] sm:h-[400px] bg-lime-300"></div> */}
                        <Backdrop />
                        <div className="flex relative">
                            <div className="w-16">
                                <MainNav />
                            </div>
                            <div className="w-full">
                                <ToasterModalProvider />
                                <AddNewProductModal
                                    products={products}
                                    categories={categories}
                                    units={units}
                                />
                                {children}
                                <Toaster />
                            </div>
                        </div>
                    </ThemeProvider>
                </Providers>
            </body>
        </html>
    );
}
