import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { AddNewOrgModal } from "./components/modals/AddNewOrgModal";
import { SessionProvider } from "next-auth/react";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Vazirmatn({ subsets: ["arabic"], weight: "400" });

export const metadata: Metadata = {
    title: "Invoice Management System",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ar" dir="rtl" className="light">
            <body
                className={`${inter.className} h-screen relative w-full mx-auto bg-[#fafafa]`}
            >
                <SessionProvider>
                    <ChakraProvider>
                        <div className="">
                            <AddNewOrgModal />
                            {children}
                        </div>
                    </ChakraProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
