import type { Metadata } from "next";
import { Almarai } from "next/font/google";

import "./globals.css";
import ToasterModalProvider from "./providers/toaster";
import Image from "next/image";
import bgIamge from "../../public/bg2.svg";

const inter = Almarai({ subsets: ["arabic"], weight: "400" });

export const metadata: Metadata = {
    title: "Invoice Management System",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ar" dir="rtl" className="light">
            <body className={`${inter.className} relative w-full mx-auto`}>
                <div className="absolute inset-0 max-h-screen overflow-hidden">
                    <Image src={bgIamge} alt={"bg"} className="object-none" />
                </div>
                {children}
                <ToasterModalProvider />
            </body>
        </html>
    );
}
