import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./../globals.css";
import prismaDb from "@/lib/prisma";
import { auth } from "auth";
import { redirect } from "next/navigation";
import OpenModal from "@/components/openModal";

const inter = Vazirmatn({ subsets: ["arabic"], weight: "400" });

export const metadata: Metadata = {
    title: "Invoice Management System",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const user = await auth();
    // console.log(user);
    if (!user?.user.id) {
        redirect("/login");
    }
    const store = await prismaDb.organization.findFirst({
        where: {
            ownerId: user?.user.id,
        },
    });
    if (store) {
        redirect(`/${store.id}`);
    }
    return <>{children}</>;
}
