/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Omdyr3vcRmg
 */
import {
    SelectValue,
    SelectTrigger,
    SelectLabel,
    SelectItem,
    SelectGroup,
    SelectContent,
    Select,
} from "@/components/ui/Select";

export function Selectv0() {
    return (
        <Select>
            <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Select a category" />
            </SelectTrigger>
            <SelectContent>
                <SelectGroup>
                    <SelectLabel>Categories</SelectLabel>
                    <SelectItem value="fruits">Fruits</SelectItem>
                    <SelectItem value="vegetables">Vegetables</SelectItem>
                    <SelectItem value="dairy">Dairy</SelectItem>
                    <SelectItem value="meat">Meat</SelectItem>
                    <SelectItem value="grains">Grains</SelectItem>
                </SelectGroup>
            </SelectContent>
        </Select>
    );
}
